import { Test } from './first.js';
import { Hello } from './testing.js';
import { login } from './login.js';
import {updateCustomer} from './Add/updateCustomer.js';
import { addCustomer } from './Add/addCustomer.js';
import { addDoctor } from './Add/addDoctor.js';
import { updateDoctor } from './Add/updateDoctor.js';
import { employee } from './employee.js';
import {addPatient} from './Add/addPatient.js';
import {searchDoc} from './Add/searchDoc.js';
import {newpatient} from './Add/newpatient.js';
import {callManagement} from './Add/callManagement.js';
import {addAppointment} from './Add/addAppointment.js';
import {addAppointment1} from './Add/addAppointment1.js';
import {patientdetails} from './Add/patientdetails.js';
import {searchpatient} from './Add/searchpatient.js';
import {docappointment} from './Add/docappointment.js';
import {appointmentDetails} from './Add/appointmentDetails.js';
import {searchDocemp} from './Add/searchDocemp.js';
import {appointmentDetails1} from './Add/appointmentDetails1.js';
import {oldpatient} from './Add/oldpatient.js';